# Generated by Django 4.2.7 on 2025-05-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_microempresasatelite_direccion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalificacionProducto',
        ),
    ]
